/**
 * Test PDF Generation
 * Simple script to test if PDFKit is working correctly
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit');
import { writeFileSync } from 'fs';
import { join } from 'path';

async function testPDFGeneration() {
  console.log('🧪 Testing PDF generation...\n');

  try {
    // Create a simple PDF
    const doc = new PDFDocument({
      size: 'A4',
      layout: 'landscape',
    });

    const chunks: Buffer[] = [];
    
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    
    await new Promise<void>((resolve, reject) => {
      doc.on('end', () => resolve());
      doc.on('error', reject);

      // Add some content
      doc
        .fontSize(24)
        .text('Test Certificate', 100, 100);

      doc
        .fontSize(16)
        .text('This is a test PDF generated by PDFKit', 100, 150);

      doc.end();
    });

    const pdfBuffer = Buffer.concat(chunks);
    
    // Save to file
    const outputPath = join(process.cwd(), 'test-certificate.pdf');
    writeFileSync(outputPath, pdfBuffer);

    console.log('✅ PDF generation successful!');
    console.log(`📄 Test PDF saved to: ${outputPath}`);
    console.log(`📊 PDF size: ${pdfBuffer.length} bytes\n`);

    return true;
  } catch (error) {
    console.error('❌ PDF generation failed:', error);
    if (error instanceof Error) {
      console.error('Error message:', error.message);
      console.error('Error stack:', error.stack);
    }
    return false;
  }
}

testPDFGeneration()
  .then((success) => {
    process.exit(success ? 0 : 1);
  })
  .catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
